name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Titillium
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: assets/fonts/titillium/TitilliumWeb-Black.ttf
          weight: 900
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather-Light.ttf
          weight: 300
        - asset: assets/fonts/merriweather/Merriweather-Regular.ttf
        - asset: assets/fonts/merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/merriweather/Merriweather-Black.ttf
          weight: 900
    - family: Bangers
      fonts:
        - asset: assets/fonts/bangers/Bangers-Regular.ttf
          weight: 400
